#+TITLE:       读好书，好读书，不求甚解
#+AUTHOR:      Yihulee
#+EMAIL:       lishuhuakai@gmail.com
#+DATE:        2016-06-03 周五
#+URI:         /blog/%y/%m/%d/读好书，好读书，不求甚解
#+KEYWORDS:    书，学习
#+TAGS:        技巧
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: 我在扯淡

怎样真正地，快速地学好一样东西，我的建议是读书，而且必须是读好书，越是大家和大牛，就越能把深刻复杂的东西讲得深入浅出，反而一些垃圾的东西喜欢卖弄高深的概念，让人云里雾里，不知所云。

我手上的这本《数值计算方法》就是非常好的例子，通篇在堆公式，我严重怀疑作者是否真正搞懂了数值计算，或者是作者只是从这里，从那里抄来了一些东西。看这本书真他妈费劲。因为突然之间就会冒出了一个莫名其妙的符号，这啥玩意，我翻了整本书都没发现作者有所标注，还有非常有意思的是，我用计算机稍微验证了一下书中某道题目，它居然算错了，真是十分令人寻味啊。对于这种东西，我真的只能称之为垃圾，这世道这种垃圾都能被出版，真是活久见了。

与之对比的，然后我手中还有一本教材，叫《数值分析》，豆瓣评分9.4，它由浅入深，读了之后发现那些高深的东西并非凭空出现，它们的由来是非常自然的，短短几个小时，我看懂了上本书七八页都扯不清的一些玩意。

读那些垃圾的东西真是费我钱财费我时间，所以真正要学一些什么玩意的时候，去豆瓣搜一些相关的书，最好评分在8.5以上，那些烂书就不要翻了。

你还别说，我觉得我本科的时候真的走了很多的弯路，虽然说我自己感觉挺努力的，但是我发现自己学的确实不怎么样。很简单的，就拿我的高数来说吧，我是真的很想把高数学好的，上课也认真听讲，考研的时候还特地去听了一遍蔡高厅老先生的公开课，恶补了一下，虽然比第一次感觉好了太多，但是有些东西仍然理不清，还有就是即使当时理解了一些抽象的东西，事后淡忘得非常快。

现在如果说让我告诉当初的我如何来学习的话，我会这么告诉自己，兄弟，首先什么都不管，到豆瓣读书去，搜一搜相关的教科书，搞几本9分以上的经典，要么买，要么到图书馆去借，把它们用作参考书目，因为我发现，当初本科用的教材，甚至研究生考试指定的教材，事实上它们的评分都是异常的低，这么一些大家都不喜欢的东西，说得难听点，真的是在浪费当初的我的年少的时光，读些经典的东西，再加上认真的听课的话，我想效果会非常的理想。

如果你看到了这篇文章，而你又寻求高效率的学习的话，你真是幸运，我磕磕碰碰走了这么久才品味到的东西，你现在就已经知道了。
