#+TITLE:       谁还记得那个落难的王子呢？
#+AUTHOR:      Yihulee
#+EMAIL:       lishuhuakai@gmail.com
#+DATE:        2016-05-25 周三
#+URI:         /blog/%y/%m/%d/谁还记得那个落难的王子呢？
#+KEYWORDS:    落难的王子
#+TAGS:        感悟
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: 感想

#+BEGIN_QUOTE
有一个王子，生性多愁善感，最听不得悲惨的故事。每当左右向他禀告天灾人祸的消息，他就流着泪叹息到：“天哪，太可怕了！这事落到我头上，我可受不了！”

可是，厄运终于落到了他的头上，在一场突如其来的战争中他的父王被杀，母后受辱自尽，他自己也被敌人掳去当了奴隶，受尽非人的折磨。当他终于逃出虎口时他已经成了残废，从此流落异国他乡，靠行乞度日。

我是在他行乞时遇到他的，见他相貌不凡，便向他打听身世。听他说罢，我早已泪流满面，发出了他曾经有过的同样的叹息：

“天哪，太可怕了！这事落到我头上我可受不了！”

谁知他正色道——

“先生，请别说这话。凡是人间的灾难，无论落到谁头上，谁都得受着，而且都受得了——只要他不死。至于死，那更是一件容易的事了。”

落难的王子撑着拐杖远去了。有一天，厄运也落到了我的头上，而我的耳边也响起了那熟悉的叹息：

“天哪，太可怕了……”
#+END_QUOTE

落难的王子这篇文章大概是初中的时候学的,这些天里，我的脑海里总是浮想起王子的那句话： *凡是人间的灾难，无论落到谁头上，谁都得受着，而且都受得了——只要他不死。至于死，那更是一件容易的事了。*

我突然对王子的遭遇感同身受，没有什么东西是受不住的，只要你不死，你都得受着。这段时间里，遭遇到了过去那些年不曾接触过的事情，特别是对于我这种内敛的人来说，有些事情会让我感到非常难受，非常迷惘。在过去的一段时间里，我的思绪一直在挣扎着，害怕着，有的时候我想逃避掉这些事情，什么事情也不干，可是我的良知告诉我说，不行，这个事情你必须得上，有些事情不是你不想做就能够不做的，有些事情你始终要面对的，逃避只会使得这些事情越变越糟糕。所以你要直面挑战。那段时间晚上一直失眠，昏昏沉沉的。

是啊，有些东西，你还真的受着。

那些杀不死你的，终于都会使你变得更加强大。

有些事情，经历了，才会觉得，不过如此！

所谓困难越难我越浪。
