#+TITLE:       在最美的时光里错过
#+AUTHOR:      Yihulee
#+EMAIL:       Yihulee@gmail.com
#+DATE:        2016-02-03 周三
#+URI:         /blog/%y/%m/%d/在最美的时光里错过
#+KEYWORDS:    错过
#+TAGS:        随笔
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: 最美的东西总在回忆里
  半年前写的大学总结篇，感觉很难写，今天算是补一个坑吧！
* 在最美的时光里错过

** 关于答辩

  今天刚刚答完辩，刚上台的时候，非常紧张，讲着讲着，心情一下子就平复下来了，突然也感觉一切貌似没有想象中的可怕，究竟讲了一些啥，我也不知道。

  不过这场答辩对我的触动颇大，因为貌似不起眼的计算机学院，牛人还是有不少的，我在座位上坐了半个小时，就碰到了两位。

  A同学做了个类似于百度知道的问答平台，一开口就是推荐算法，他做的东西，麻雀虽小，五脏俱全，我很难相信，这东西能在半年内完成，因为工作量是在有些大。然而他确实完成了。
  
  B同学更不得了，实现了一个推荐系统，用的好像是Hadoop之类的东西，说实话，本人实在是孤陋寡闻，大学四年，真没听过这玩意，不过答辩的老师倒是和B同学聊得挺high的，听两人的口气，B同学的作品貌似和数学联系非常紧密，其中涉及了线性矩阵等一系列高大上的玩意，好吧，你们high吧，我总之听不懂。

  碰到那两个家伙，我真心紧张，因为就怕货比货，我做了什么，仅仅是一个垃圾邮件过滤器，仅仅实现了贝叶斯算法，邮件接收发送等一些常用的基本邮件操作，自己还满以为挺不错的，毕竟测试的垃圾邮件过滤可以达到98%左右，不过和人家一比，瞬间感觉low了一截。不过我可是问心无愧的，因为都是代码，论文什么的自己写的。

** 关于毕业设计

  毕业设计这东西，我花了很大的精力，用了大约两个月的时间来做，花在算法上的时间顶多也就15天，包括查资料，编码等，大部分时间花在了界面上，不得不说，用MFC来编界面工作量实在是大，比我的核心代码的工作量要大得多，这次编码，倒有些主次不分明了。

  不过，经过这一次，对于MFC的理解算是又进了一个台阶，在界面这一个层次，MFC最低级的水准是拖控件，最高水准是自己做出一个非常漂亮非常实用的控件，别小看这种东西，这必须要懂得非常多的东西，像是消息映射，反射，自绘，GDI，还包括消息的截获等东西，做出来了，水准立马就上来了。一年前我还属于最低级，只会拖控件，只懂得一些皮毛的GDI，然后将近一年的考研，忘得差不多了，现在拾起来了，继续向前冲锋，每进一步都感到MFC的难度，至少没有两年的时间，我不敢说自己能够精通这东西。个人觉得，最牛的还是编写那些界面库的人，真心只能膜拜。 
  (注: 今天我可不这么认为，人变得可是真快啊！)

  将来还会不会使用MFC，我也不知道，这东西现在估计不是很火，我也没看见身边有多少人用，微软虽然巨硬，但是也在走下坡路，用户正在从windows流向其他平台，我不知道window是否还是辉煌依旧。说到底，MFC也只是框架而已，换个框架，也可以干活，个人觉得QT比MFC更有前途，linux将来的应用场景比window更宽广,将来还是会逐步走向linux吧。

  (注: 半年前我的眼界还很窄，看不到一些东西，现在我可以很肯定地说，MFC已死，现在如果把时间花在MFC上很不值，除非你要维护一些老的项目，有人说可以学习MFC的框架设计，不过那个东西我觉得意义不大，因为过于复杂，且年代久远，现在有很多比MFC优秀简洁的框架。在另一个层面上来说，CS大约已死，BS正大行其道。)

  总之毕业设计这玩意我算是认真的啦，同学敷衍的一大堆，有的同学跑到淘宝去买代码和论文，有的干脆
** 关于这四年 

  然后呢，扯完了这些，就是完结了，四年啦！四年过完之后，突然发现自己会的东西依旧很少，虽然我做过很多事情，比如说过了六级，考上了研，拿过专业第一。现在发现，这些并没有什么卵用。甚至自己学的这些东西都没有什么用，将来不从事这一方面的职业的话，学到的一些结论和概念等于白学。别人说，重要的不是知识本身，学习的方法比知识本身更加重要。其实我也不知道，或许体会还没达到那一种境界吧！

  今天拍完了毕业照，发现大学真的结束了，今天过后，班上的同学就要走了，或是去旅游，或是去工作，总之将来的某一天都不会比今天来得更加齐整了，下一次我们再相见，或许是五年后，十年后，十五年后了。

  突然觉得很伤感，四年的光华就如此逝去了，我并不会说，四年眨眼就过去了，因为在我的印象当中，这四年，的确是挺长的一段，我做过很多事情，也经历过很多事情。

  我所知道的，我正在努力做着一件事情，那就是让自己在某一方面成为高手，让自己获得一门足矣养活自己的手艺。我佩服的人是日本的矢野洋一老先生，他花了一辈子的时间来做寿司，或者说他一辈子只在做做寿司这一件事，最终的结果是，他的寿司手艺在日本达到了天王水准。我也希望能像老先生一样，用一生去做一件事情，所以现在，我努力地学着一门门计算机专业应该了解的课程，尽力地去学好它们。我希望时光流转，终有一天，我能成为一个高手，我同时也希望，计算机是一门值得我奉献终生的事业。

** 再也见不到的那个人啦

  有些人，一旦错过，这辈子或许也都不会相见。比如说那个令我心动的她。遇见她，是在考研的日子里，看见她，是在十教附二的考研教室，她长发及腰，很优雅，俯首做题的样子很漂亮，恰好是我欣赏的类型。

  考研的那些日子里，经常碰见她，她总是从我的座位前走过，走到后面去看书，到了暑假复习的时候，我的战场转移到了十教附一，大概一个多月吧，我不记得，没有见过她，后来不知道怎么的，她又出现在了我所在的教室里，她坐在最前一排，而我，在最后一排，她的突然出现，我真的挺高兴的，有时候做题做累了，远远从背后望她一眼，觉得内心充满了动力。

  我并不知道她要考去哪里，甚至她叫什么我都不知道，知道又有什么用呢？我时常这么想，既然还未开始，就应该让它永远地结束。

  暑假过完之后，我已经很难在再看到她了，我时常去十教附二，去图书馆，一个人默默地享受着考研的孤独，莫名的孤独。整整一个考研季，我并没有固定的座位，每天都背起厚厚的书包，在教室里，图书管里漂流。她的位置也是飘忽不定的。我也说不清她什么时候回来，什么时候不会来。

  有时候还是会遇见的，晨读的时候，晚自习的时候，还是那句话，看见她，我挺兴奋的。我说不清那种感觉，像是老友的重逢，像是亲人的团聚。

  冬天的时候，天气一天比一天冷，十教附二并没有空调，即使很难受，还是得忍着，图书馆可好的多，虽然也没空调，但是人多，因此，我没事就去图书馆坐，这样一来，看见她的日子更加少了，不过，面对一天一天逼近的考试，我没心思去管这事。

  我并非校草，也不是大款，我给不了山盟海誓，天崩地裂，我有时候甚至感觉自己没有资格去喜欢一个人，但是我真心希望她幸福，好姑娘应该有一个好的归宿。

  然后就考完了，面试完了，四月的一天早上，我看见了她，向我走来，她依然是那个她，优雅，宁静，我也依然是那个我，我们依然擦肩而过，我回头看了一眼，很开心。

  然后我再也没有见过她，仿佛这个世界上她从来就没有出现过一样。我时常去十教附一转悠，教室里坐的都是新鲜的面孔，同我一同考研的人都消失了，就像他们从来就没有出现过一样。

** 关于选择

  很多事情其实都是无解的，就像选择一般，这个世界上并没有绝对对的或者绝对错的选择，当初选择考研，我斟酌了很久，我不知道那条路更加适合我，当然，即使现在考上了，我依旧不知道，当初的选择是否正确，我现在任然在动摇，如果当初不选择考研，我的人生又会怎么样呢？

  如果我当初选择得过且过，我今天又会在哪里呢？  

  世界上有很多分叉口，当初微不足道的一个选择导致的结果将会千差万别，而这，不就是我们的人生么？

  我们喜欢做的事情就是走在一条道上，想念另一条道路上的繁荣兴盛，至少我是这样的。

  错过了一些人，一些景象，你永远也回不了头。
